# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-09 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180609_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='alumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Event'),
        ),
    ]
