# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-09 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180609_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 9, 16, 47, 55, 176766, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
