# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reserv_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
